name: Build and push feathers on tag

on:
  push:
    branches: [ production ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        tags: acdi/efem-users-feathers:production
        push: true
